M48
; DRILL file {KiCad (7.0.0)} date Mon Nov 20 00:41:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-20T00:41:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X101.632Y-127.917
X107.315Y-128.97
T2
X181.64Y-127.126
X183.353Y-132.015
X183.653Y-126.843
T0
M30
